---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: 30 6 * * *
      timezone: Europe/London
    cooldown:
      default-days: 7
    labels:
      - dependencies

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: cron
      cronjob: 30 6 * * *
      timezone: Europe/London
    cooldown:
      default-days: 7
      semver-minor-days: 9
      semver-major-days: 11
    labels:
      - dependencies
