#!/bin/bash -e

# Build script to cross-compile Dropbear for Android
# Copyright © 2020 Matt Robinson

if [ -z "$ANDROID_NDK_HOME" ]; then
    if [ "$ANDROID_HOME" ]; then
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
    else
        echo "Either ANDROID_NDK_HOME or ANDROID_HOME must be set" >&2
        exit 1
    fi
fi

TARGET=${TARGET:-armv7a-linux-androideabi}

if [[ "$TARGET" =~ ^(aarch64|x86_64)- ]]; then
    PLATFORM=21
else
    PLATFORM=16
fi

toolchain=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64


cd dropbear

# Generate configure and config.h
autoconf
autoheader

./configure --host="$TARGET" \
    AR="$toolchain/bin/${TARGET/armv7a/arm}-ar" \
    CC="$toolchain/bin/$TARGET$PLATFORM-clang" \
    LD="$toolchain/bin/${TARGET/armv7a/arm}-ld" \
    RANLIB="$toolchain/bin/${TARGET/armv7a/arm}-ranlib" \
    STRIP="$toolchain/bin/${TARGET/armv7a/arm}-strip"

cp ../localoptions.h .

make
