#!/bin/bash -e

# Copyright © 2020-2021 Matt Robinson
#
# SPDX-License-Identifier: MIT

if [ -z "$ANDROID_NDK_HOME" ]; then
    if [ "$ANDROID_HOME" ]; then
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
    else
        echo "Either ANDROID_NDK_HOME or ANDROID_HOME must be set" >&2
        exit 1
    fi
fi

TARGET=${TARGET:-armv7a-linux-androideabi}

if [[ "$TARGET" =~ ^(aarch64|x86_64)- ]]; then
    PLATFORM=21
else
    PLATFORM=16
fi

toolchain=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
version=$(cat dropbear-version)
patchcount=$(find . -maxdepth 1 -name "*.patch" | wc -l)

[ -d buildinfo ] || mkdir buildinfo
echo "$version${patchcount+p$patchcount}" > buildinfo/release
grep Pkg.Revision "$ANDROID_NDK_HOME/source.properties" | \
    cut -d ' ' -f 3 >> buildinfo/ndkver

git clone --branch "$version" --depth 1 https://github.com/mkj/dropbear.git
cd dropbear

if [ "$patchcount" -gt 0 ]; then
    for patch in ../*.patch; do
        patch -p1 < "$patch"
    done
fi

# Generate configure and config.h
autoconf
autoheader

./configure --host="$TARGET" \
    AR="$toolchain/bin/llvm-ar" \
    CC="$toolchain/bin/$TARGET$PLATFORM-clang" \
    RANLIB="$toolchain/bin/llvm-ranlib" \
    STRIP="$toolchain/bin/llvm-strip"

cp ../localoptions.h .

make PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" SCPPROGRESS=1
